START TRANSACTION;
ALTER TABLE "Message" DROP CONSTRAINT "FK_Message_User_UserId";

DROP INDEX "IX_Message_UserId";

ALTER TABLE "Message" DROP COLUMN "UserId";

ALTER TABLE "Message" ADD "ContentStored" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Message" ADD "SMTPAccountId" integer;

CREATE TABLE "MessageRecipient" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" character varying(255) NOT NULL,
    "Email" character varying(254) NOT NULL,
    "Name" character varying(255),
    "Type" integer NOT NULL,
    "Position" integer NOT NULL,
    CONSTRAINT "PK_MessageRecipient" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageRecipient_Message_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Message" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Message_SMTPAccountId" ON "Message" ("SMTPAccountId");

CREATE INDEX "IX_MessageRecipient_MessageId" ON "MessageRecipient" ("MessageId");

ALTER TABLE "Message" ADD CONSTRAINT "FK_Message_SMTPAccount_SMTPAccountId" FOREIGN KEY ("SMTPAccountId") REFERENCES "SMTPAccount" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260831162309_MessageSmtpAccountAndRecipients', '10.0.11');

COMMIT;

